### ISSUE TITLE
Is this needed? 

### ISSUE THREAD

**Issue by francopestilli** [PESTILLILAB/PESTILLILAB.github.io#13]
public/categories/index.xml
https://github.com/PESTILLILAB/PESTILLILAB.github.io/tree/main/archetypes

Are there other files/folders that we can eliminate?

Shall we clean up the folders? @bhatiadheeraj

**Comment by bhatiadheeraj** [comment]
The archetypes folder is part of Hugo and the public folder is generated by Hugo which is the folder generated to publish the website.

https://gohugo.io/content-management/archetypes/
