### ISSUE TITLE
Improving the timeline component

### ISSUE THREAD

**Issue by anibalsolon** [PESTILLILAB/PESTILLILAB.github.io#19]
The timeline as it is now is difficult to navigate and does not look good (colors, text sizing, too much empty space, being boxed for scroll).

Some suggestions:
- Match the color scheme
- Increase size by 30% (we need to also think about accessibility)

About scrolling, having a horizontal timeline would help, since its scrolling works perpendicular to the page scroll. Disable default scrolls. A year navigator above the timeline, the timeline with the points, and scroll to the publication when a point is clicked. The points needs to always be shown in the timeline, if not, the visitor will not have a good idea when the publications will end. 

If vertical is still preferred, I suggest to drop the 'zebra' positioning of the items, keep the timeline in the left and text in the right. Same way, with year navigator and always showing all the points. And remove default scrolls, especially the horizontal one.

**Comment by bhatiadheeraj** [comment]
@francopestilli should I remove the box for scroll and the zebra positioning of items?

**Comment by francopestilli** [comment]
I like the Google photos scroll and timeline. It appears as you try to move
