### ISSUE TITLE
Improve clarity on banners/sliders active/inactive

### ISSUE THREAD

**Issue by francopestilli** [PESTILLILAB/PESTILLILAB.github.io#24]
If I go to a folder like this one: https://github.com/PESTILLILAB/PESTILLILAB.github.io/tree/main/content/team
I see multiple-sliders, but only one of them is-actively displaying. How do I control that?
It is not clear from the file structre which one is ‘active’
Also on the sliders there, the text associated with the slider (the text in the MD table) does not seem to show. how so?
also clarifying the difference between slider and banner would be key
they seem to serve the same purpose

@bhatiadheeraj

**Comment by francopestilli** [comment]
Also how can edit the text on the banner/slider?

**Comment by francopestilli** [comment]
Does 'active' means that it rotates or that it is active so in use?

**Comment by francopestilli** [comment]
How can I control the order of a slider? 
I would like to build story with the tag-lines of each slider

**Comment by francopestilli** [comment]
for exampleI added a new banner https://github.com/PESTILLILAB/PESTILLILAB.github.io/blob/main/content/home/slider_cloud_technology.md

I changed onlytext, image and added 'active' 

now the other banners do not show any longer and the one I prefer to be the first to show(the city of austin) does not show first

**Comment by francopestilli** [comment]
Why after making the three sliders in 'team' only one slider is visible and the same slider shows up also as a team member? https://pestillilab.github.io/team/

**Comment by bhatiadheeraj** [comment]
https://github.com/PESTILLILAB/tacademia.hugo#create-front-page-slides-using-markdown 
We plan to remove the carousel/jumbotron with the newer component. 
For slidiers 
The one which you want to show first can be shown with the extra tag of active and the rest you can control with the parameter weight.
