### ISSUE TITLE
Edits after Release of 08/16/2022

### ISSUE THREAD

**Issue by francopestilli** [PESTILLILAB/PESTILLILAB.github.io#29]
1. Move 'growing' brain up, closer to the level of the tag line of the lab. Now the brain is too low and it does not appear symmetric and the growing threads from the brain hide the text of the bow below.
2. Decrease size of footer to 50% of current size
3. Decrease team page (font and images) to 70% of current size)
4. Decrease font size of subtitle of each collaborators and alumni compared to name of person. The subtitle "Associate Professor, Department of Statistics, The University of British Columbia. Together we are developing approaches to tractography methods optimization" Is too big (it should be the same as the bio of Franco)
5. Add short subtitle to current members
6. Add info about how to update map. The coordinates are off

@anibalsolon 
comments from discussion with @giulia-berto

**Comment by anibalsolon** [comment]
@francopestilli what should be the priority of these issues?

**Comment by francopestilli** [comment]
The above would be fine thanks 😌

**Comment by anibalsolon** [comment]
@francopestilli @giulia-berto please take a look on the last version: https://pestillilab.github.io/

The map coordinates are at https://github.com/PESTILLILAB/PESTILLILAB.github.io/blob/main/data/institutions.toml
The link is in the README.md.

**Comment by giulia-berto** [comment]
@anibalsolon great job! I like the current font size. In my opinion, now the 'growing' brain is too small, the previous size was nicer.

**Comment by francopestilli** [comment]
I second the comment. 
@anibalsolon Is there a way we can play around with sizing – I ask not to bother you again with this :-)

**Comment by anibalsolon** [comment]
Yeah I tried to increase a bit- it is hard to make it work in all resolutions. I can explore a bit more.

**Comment by francopestilli** [comment]
All this have now been integrated. Thanks @anibalsolon and @giulia-berto !
