### ISSUE TITLE
I confirm

### ISSUE THREAD

**Issue by francopestilli** [PESTILLILAB/PESTILLILAB.github.io#7]
The website is currently cooking my laptop.
Running on MacBook Pro 

![image](https://user-images.githubusercontent.com/2119795/137043924-d17bf8e1-e542-478f-b056-3e29cba9747a.png)

![image](https://user-images.githubusercontent.com/2119795/137043963-f9e3afad-4c3e-4ca7-a6fb-25ca94905cc6.png)

**Comment by anibalsolon** [comment]
Yes, the images are huge- the plot image with label 'Example Slide' has 13MB. It may be it.
